services:

  postgres:
    image: postgres:17
    container_name: pizzaplaza-postgres
    environment:
      POSTGRES_DB: pizzaplaza_db
      POSTGRES_USER: fernando
      POSTGRES_PASSWORD: fernando
    ports:
      - "5433:5432"
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    volumes:
      - ./auth/privateKey.pem:/privateKey.pem
      - ./auth/publicKey.pem:/publicKey.pem

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    volumes:
      - ./auth/publicKey.pem:/publicKey.pem

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - product-service
      - order-service
      - user-service

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    volumes:
      - ./auth/publicKey.pem:/publicKey.pem

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    volumes:
      - ./auth/publicKey.pem:/publicKey.pem

  app-front:
    build:
      context: ./app-front
      dockerfile: Dockerfile
    container_name: pizzaplaza-front
    ports:
      - "4200:80"
    depends_on:
      - api-gateway

  seeder:
    image: postgres:17
    container_name: pizzaplaza-seeder
    depends_on:
      - auth-service
      - user-service
      - product-service
    environment:
      PGPASSWORD: fernando
    volumes:
      - ./docker/seed.sql:/seed.sql
    entrypoint: >
      sh -c "
        echo 'Aguardando serviços inicializarem...' &&
        sleep 20 &&
        psql -h postgres -U fernando -d pizzaplaza_db -f /seed.sql &&
        echo 'Seed concluído.'
      "
    restart: "no"
