quarkus.http.port=8081

%dev.mp.jwt.verify.publickey.location=../auth/publicKey.pem
%prod.mp.jwt.verify.publickey.location=/publicKey.pem
mp.jwt.verify.issuer=auth-service

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=fernando
quarkus.datasource.password=fernando
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pizzaplaza_db
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/pizzaplaza_db

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.persistence-xml.ignore=true
quarkus.hibernate-orm.active=true
quarkus.hibernate-orm.database.default-schema=user_service
quarkus.hibernate-orm.packages=br.com.pizzaplaza.userservice.entities
