quarkus.http.port=8083

quarkus.swagger-ui.always-include=true 

mp.jwt.verify.issuer=auth-service
mp.jwt.verify.publickey.location=../auth/publicKey.pem

#Data source
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=fernando
quarkus.datasource.password=fernando
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pizzaplaza_db
quarkus.hibernate-orm.database.default-schema=product_service

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.persistence-xml.ignore=true
quarkus.hibernate-orm.active=true
quarkus.hibernate-orm.packages=br.com.pizzaplaza.contracts
